version: '3.8'

services:
  createuser:
    image: pamendeza/createuser:latest
    ports:
      - "3001:3001"
    restart: always 

  readuser:
    image: pamendeza/readuser:latest
    ports:
      - "3002:3002" 
    restart: always

  updateuser:
    image: pamendeza/updateuser:latest
    ports:
      - "3003:3003" 
    restart: always  

  deleteuser:
    image: pamendeza/deleteuser:latest
    ports:
      - "3004:3004" 
    restart: always  
