version: '3.8'

services:
  createbeneficiary:
    image: pamendeza/createbeneficiary:latest
    ports:
      - "8001:8001"
    restart: always

  readbeneficiary:
    image: pamendeza/readbeneficiary:latest
    ports:
      - "8002:8002"
    restart: always

  updatebeneficiary:
    image: pamendeza/updatebeneficiary:latest
    ports:
      - "8003:8003"
    restart: always  

  deletebeneficiary:
    image: pamendeza/deletebeneficiary:latest
    ports:
      - "8004:8004"
    restart: always
