version: '3.8'

services:
  uploadvoucher:
    image: pamendeza/uploadvoucher:latest
    ports:
      - "5005:5005"
    restart: always

  viewvoucher:
    image: pamendeza/viewvoucher:latest
    ports:
      - "5006:5006"
    restart: always
