name: Registry image

on:
  push:
    branches: ["QA"]

jobs:
  # USER DOMAIN CONTINOUS DEPLOYMENT
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      modified_dirs: ${{ steps.changed_dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last sha commit
        id: get_sha
        run: |
          before_sha=$(git log -1 --skip=1 --pretty=format:"%H")
          echo "::set-output name=sha::$before_sha"

      - name: Detect modified directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ steps.get_sha.outputs.sha }} ${{ github.sha }} | cut -d/ -f2 | sort -u | tr -d '\n' | sed 's/ //g' )
          echo "::set-output name=dirs::$CHANGED_DIRS" 
          echo "CHANGED_DIRS: $CHANGED_DIRS" 

  login-push-usercreate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'createuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_CREATEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userread:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'readuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_READUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userupdate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'updateuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPDATEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userdelete:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'deleteuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_DELETEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  ec2-cd-userdomain:
    needs: [login-push-usercreate, login-push-userread, login-push-userupdate,login-push-userdelete]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_USERDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_USERDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  # SECURITY DOMAIN CONTINOUS DEPLOYMENT
  login-push-jwtService:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'jwtservice')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_JWTSERVICE }}
      domain_name: ${{ secrets.SECURITY_DOMAIN_NAME }}

  login-push-signinService:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'signinservice')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_SIGNIN }}
      domain_name: ${{ secrets.SECURITY_DOMAIN_NAME }}

  login-push-signoutService:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'signoutservice')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_SIGNOUT }}
      domain_name: ${{ secrets.SECURITY_DOMAIN_NAME }}

  ec2-cd-securitydomain:
    needs: [login-push-jwtService, login-push-signinService, login-push-signoutService]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_SECURITYDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_SECURITYDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.SECURITY_DOMAIN_NAME }}

  # TRANSACTION DOMAIN CONTINOUS DEPLOYMENT
  login-push-transactioncreate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'createtransaction')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_CREATETRANSACTION }}
      domain_name: ${{ secrets.TRANSACTION_DOMAIN_NAME }}

  login-push-transactionread:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'readtransaction')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_READTRANSACTION }}
      domain_name: ${{ secrets.TRANSACTION_DOMAIN_NAME }}

  login-push-transactionupdate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'updatetransaction')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPDATETRANSACTION }}
      domain_name: ${{ secrets.TRANSACTION_DOMAIN_NAME }}

  ec2-cd-transactiondomain:
    needs: [login-push-transactioncreate, login-push-transactionread, login-push-transactionupdate]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_TRANSACTIONDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_TRANSACTIONDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.TRANSACTION_DOMAIN_NAME }}

  # AWSUTILS DOMAIN CONTINOUS DEPLOYMENT
  login-push-uploadvoucher:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'uploadvoucher')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPLOADVOUCHER }}
      domain_name: ${{ secrets.AWS_DOMAIN_NAME }}

  login-push-viewvoucher:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'viewvoucher')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_VIEWVOUCHER }}
      domain_name: ${{ secrets.AWS_DOMAIN_NAME }}

  ec2-cd-userdomain:
    needs: [login-push-uploadvoucher, login-push-viewvoucher]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_AWSDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_AWSUTILS }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.AWS_DOMAIN_NAME }}

  # BENEFICIARY DOMAIN CONTINOUS DEPLOYMENT
  login-push-beneficiarycreate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'createbeneficiary')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_CREATEBENEFICIARY }}
      domain_name: ${{ secrets.BENEFICIARY_DOMAIN_NAME }}

  login-push-beneficiaryread:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'readbeneficiary')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_READBENEFICIARY }}
      domain_name: ${{ secrets.BENEFICIARY_DOMAIN_NAME }}

  login-push-beneficiaryupdate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'updatebeneficiary')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPDATEBENEFICIARY }}
      domain_name: ${{ secrets.BENEFICIARY_DOMAIN_NAME }}

  login-push-beneficiarydelete:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'deletebeneficiary')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_DELETEBENEFICIARY }}
      domain_name: ${{ secrets.BENEFICIARY_DOMAIN_NAME }}

  ec2-cd-beneficiarydomain:
    needs: [login-push-beneficiarycreate, login-push-beneficiaryread, login-push-beneficiaryupdate,login-push-beneficiarydelete]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_BENEFICIARYDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_BENEFICIARYDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.BENEFICIARY_DOMAIN_NAME }}

  # CATEGORY DOMAIN CONTINOUS DEPLOYMENT
  login-push-categorycreate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'createcategory')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_CREATECATEGORY }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}

  login-push-categoryread:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'readcategory')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_READCATEGORY }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}

  login-push-categoryupdate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'updatecategory')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPDATECATEGORY }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}

  login-push-categorydelete:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'deletecategory')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_DELETECATEGORY }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}

  login-push-categoryuser:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'usercategory')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_USERCATEGORY }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}

  ec2-cd-categorydomain:
    needs: [login-push-categorycreate, login-push-categoryread, login-push-categoryupdate,login-push-categorydelete, login-push-categoryuser]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_CATEGORYDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_CATEGORYDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      domain_name: ${{ secrets.CATEGORY_DOMAIN_NAME }}