name: Registry image

on:
  push:
    branches: ["QA"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      modified_dirs: ${{ steps.changed_dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last sha commit
        id: get_sha
        run: |
          before_sha=$(git log -1 --skip=1 --pretty=format:"%H")
          echo "::set-output name=sha::$before_sha"

      - name: Detect modified directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ steps.get_sha.outputs.sha }} ${{ github.sha }} | cut -d/ -f2 | sort -u | tr -d '\n' | sed 's/ //g' )
          echo "::set-output name=dirs::$CHANGED_DIRS" 
          echo "CHANGED_DIRS: $CHANGED_DIRS" 

  login-push-usercreate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'createuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_CREATEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userread:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'readuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_READUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userupdate:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'updateuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_UPDATEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  login-push-userdelete:
    needs: [detect-changes]
    if: contains(needs.detect-changes.outputs.modified_dirs, 'deleteuser')
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_DELETEUSER }}
      domain_name: ${{ secrets.USER_DOMAIN_NAME }}

  ec2-cd-userdomain:
    needs: [login-push-usercreate, login-push-userread, login-push-userupdate,login-push-userdelete]
    if: always()
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_USERDOMAIN }}
      ec2_key: ${{ secrets.EC2_KEY_USERDOMAIN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}

