name: User Domain Workflow deploy

on: 
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      repository_name:
        required: true
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      modified_dirs: ${{ steps.changed_dirs.outputs.modified_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect modified directories
        id: changed_dirs
        run: |
          MODIFIED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "modified_dirs=$MODIFIED" >> $GITHUB_OUTPUT

  build-image:
    if: contains(fromJson(needs.detect-changes.outputs.modified_dirs), 'createUser')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build and push Docker image
        working-directory: ./usersAdministration/${{ secrets.repository_name }}
        run: |
          docker build -t ${{ secrets.docker_username }}/createUser:latest .
          docker push ${{ secrets.docker_username }}/createUser:latest